name: Run Gradle on PRs
on: push
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Gradle Command
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: buildPlugin
        arguements: publishPlugin
