name: Build and Publish Intellij Plugin
on:
  push:
jobs:
  trigger_workflow:
     strategy:
       matrix:
         os: [ubuntu-latest]
     runs-on: ${{ matrix.os }}
     env:
         working-directory: ./tool-plugins/intellij
         publish_token: ${{ secrets.PUBLISH_TOKEN }}
         plugin_id: 13933
     steps:
       - uses: actions/setup-java@v1
         with:
           java-version: 1.8
       - uses: actions/checkout@v2
         with:
           repository: lasinicl/ballerina-lang
           ref: master
       - name: build and publish plugin
         working-directory: ${{env.working-directory}}
         run: |
              ./gradlew buildPlugin
              curl -i --header "Authorization: Bearer ${{ env.publish_token }}" -F pluginId=${{ env.plugin_id }} -F file=@my-artifact.zip -F channel=stable https://plugins.jetbrains.com/plugin/uploadPlugin
       - uses: actions/download-artifact@v1
         with:
          name: my-artifact
         
